### ISSUE TITLE
Add photo as icon for the org and the user

### ISSUE THREAD

**Issue by carols10cents** [eeyorebot/eeyore#6]
I'm just a member of the org, not an owner, so I can't do this myself ;)

Image from https://www.flickr.com/photos/jdhancock/7767340604 licensed CC BY, so give flickr user jdhancock a shout-out in the readme or something :)

A few square crops that might work:

![square-1](https://cloud.githubusercontent.com/assets/193874/13363613/41340fa6-dc98-11e5-9096-3d1733519f49.png)
![square-2](https://cloud.githubusercontent.com/assets/193874/13363616/43686880-dc98-11e5-9753-a0381bfd562a.png)
![square-3](https://cloud.githubusercontent.com/assets/193874/13363619/45e6a112-dc98-11e5-8808-ed7babab0e8e.png)

**Comment by steveklabnik** [comment]
Ugh the UI implied you'd be an owner. I added you when making the org. Will fix.

**Comment by carols10cents** [comment]
also have you made the user yet? if we want to make the user named "eeyorebot", i think we messed up naming the org that :(

**Comment by steveklabnik** [comment]
Ahhhh eff. I did not, but didn't think of that.

@eeyoretriage?

**Comment by carols10cents** [comment]
Love it. I'm going to grab it since I'm AK and assuming you're still AFK :)

**Comment by steveklabnik** [comment]
Yeah, I'm gonna add you as an org owner but will still be gone for an hour
or two <3

**Comment by ghost** [comment]
Good morning, @steveklabnik. If it is a good morning. Which I doubt.

**Comment by steveklabnik** [comment]
:heart_eyes:
